@extends('User.layout')
@section('title')
    Privacy and Policy
@endsection
@section('content')
    <main class="h-100 container" style="min-height:80vh; height:auto">

        <div class="heading mt-3 px-3 container">
            <h1 class="text-uppercase text-center fw-bold">
                Privacy Policy

            </h1>
            <p class="px-3">
                In this Privacy Policy, you will find information about how we collect, use, and safeguard your personal
                information. It also details to whom we disclose the personal information and your rights while using the
                service.
            </p>
            <p class="px-3 mt-0">

                Please note that the information collected is used to enhance the interface and optimize your searches,
                providing a better experience while using the service. By using the service, you grant us the right to
                collect and use your information in accordance with this Privacy Policy and our Terms and Conditions.
            </p>
        </div>
        <hr>
        <div class="heading">
            <h2 class="fs-3">
                Definitions and Interpretations
            </h2>
        </div>
        <div class="heading mt-3 px-3 container">
            <h3 class="text-uppercase text-start fw-bold">
                For this Privacy Policy only:
            </h3>
            <ul class="mx-3">
                <li><b>Account: </b>Any account created to use our services or platform.
                </li>
                <li><b>Company:</b> Referred to as either “The Company”, "We”, "Our" or "Us", refers to the company
                    “{{ config('setting.site_name') }}”.

                </li>
                <li><b>Country:</b> Refers to the USA.

                </li>
                <li><b>Cookies:</b> Small files placed on your device by a website, containing details of your browsing
                    history and other uses.
                </li>
                <li><b>Device:</b> Any device that can access the Service, such as a PC, cell phone, or tablet.
                </li>
                <li>
                    <b>Personal Data:</b> Any information that relates to an identified or identifiable person.
                </li>
                <li>
                    <b>Service:</b> Refers to the website <a class="fw-bold text-dark" style="text-decoration:none;"
                        href="{{ config('setting.url') }}">{{ str_replace(' ', '', strtolower(config('setting.site_name'))) }}.com</a>.
                </li>
                <li>
                    <b>Service Provider:</b> Any natural or legal person who processes data on behalf of the Company. This
                    includes third-party companies or individuals employed to facilitate the Service, provide it on behalf
                    of the Company, or assist in analyzing how the Service is used.
                </li>
                <li>
                    <b>Usage Data:</b> Data collected automatically, generated by the use of the Service or from the Service
                    infrastructure (e.g., the duration of a page visit).
                </li>
                <li>
                    <b>You:</b> The individual accessing or using the Service, or the company or other legal entity on
                    behalf of which such individual is accessing or using the Service, as applicable.
                </li>
                <li>
                    <b>Third Party:</b> Services such as Google Analytics, Google AdSense, Google AdWords, Amazon
                    Associates, ClickBank, Twitter Lead Generation, Facebook Pages, Stores, and Apps, Google Play Store,
                    Apple's App Store.
                </li>
            </ul>
        </div>
        <div class="heading">
            <h2 class="fs-3">
                Gathering and Usage of Personal Data
            </h2>
        </div>
        <div class="heading mt-3 px-3 container">
            <h3 class="text-uppercase text-start fw-bold">
                Types of Data We Collect

            </h3>
            <p>
                As you use the Service, we may ask you to provide information that can be used to contact or identify you.
                This information may include, but is not limited to:

            </p>
            <ul class="mx-3">
                <li>
                    Email Address
                </li>
                <li>
                    First and Last Name

                </li>
                <li>
                    Phone Number

                </li>
                <li>
                    Address, including State, Province, ZIP/Postal Code, City

                </li>
                <li>
                    Usage Data

                </li>

            </ul>
        </div>
        <div class="heading text-start mt-3 px-3 container">
            <h3 class="text-uppercase fw-bold">
                Tracking and Cookies

            </h3>
            <p>
                We use cookies and similar tracking technologies to track activity on our Service and store certain
                information. These include cookies and web beacons (tags or clear gifs that allow the company to count the
                users who have visited the page and used the services). These cookies are administered by third parties who
                help us analyze consumer patterns. However, you can manage the cookies collected by us.
            </p>
        </div>
        <div class="heading mt-3 px-3 container">
            <h3 class="text-uppercase text-start fw-bold">
                Uses of Your Personal Data


            </h3>
            <p>
                We may use the collected personal data for the following purposes:

            </p>
            <ul class="mx-3">
                <li><b>To Maintain Our Services:</b>Monitoring the usage of our services.

                </li>
                <li><b>To Manage Your Account: </b> Registering you to use our services and providing you access to
                    different functionalities of the website as a registered user.


                </li>
                <li><b>To Contact You:</b> Using your email address or phone number to communicate updates, offers, deals,
                    functionality changes, products, and contracted services.


                </li>
                <li><b>For the Performance of a Contract:</b> Providing services or products you have requested.

                <li><b>To Attend to Your Requests:</b> Managing and addressing the requests you make to us.
                </li>
                <li>
                    <b>In Case of Merger or Acquisition:</b>Your information may be used during business transfers, such as
                    mergers, restructuring, reorganization, dissolution, or sale of assets.

                </li>
                <li>
                    <b>For Other Purposes:</b> Analyzing, evaluating, and improving services and user experience.
                </li>

            </ul>
        </div>
        <hr>
        <div class="heading text-start mt-3 px-3 container">
            <h3 class="text-uppercase fw-bold">
                Sharing Your Personal Data
            </h3>
            <p>
                The company may share your information in the following scenarios:

            </p>
            <ul class="list-unstyled">
                <li><b>With Service Providers: </b>To monitor, analyze, and improve your experience.
                </li>
                <li><b>For Business Transfers: </b>During business transfers such as mergers, restructuring, reorganization,
                    dissolution, or sale of assets.

                <li><b>With Affiliates: </b> With our affiliates, who will comply with this Privacy Policy.

                </li>
                <li>
                    <b>With Government Agencies: </b>If required by law or for legal processes.

                </li>
            </ul>
            <p>
                <b> Note: </b>We may disclose information to other parties but will require your consent before doing so.
            </p>
        </div>
        <div class="heading text-start mt-3 px-3 container">
            <h3 class="text-uppercase fw-bold">
                Data Retention

            </h3>
            <p>
                We will retain your personal data only as long as necessary for the purposes set out in this Privacy Policy
                and to comply with legal obligations, resolve disputes, and enforce legal agreements. We may also retain
                your data for internal analysis to improve security and user experience.
            </p>
        </div>
        <div class="heading text-start mt-3 px-3 container">
            <h3 class="text-uppercase fw-bold">
                Disclosure of Your Personal Data

            </h3>
            <p>
                The company will disclose your personal data in the case of mergers, dissolution, liquidation, or
                bankruptcy. It may also share the information to comply with legal proceedings or requests from law
                enforcement agencies.

            </p>
        </div>
        <div class="heading text-start mt-3 px-3 container">
            <h3 class="text-uppercase fw-bold">
                Security of Your Personal Data


            </h3>
            <p>
                The company takes great care to protect your personal data and has implemented several measures to prevent
                data breaches. However, no electronic storage medium is 100% secure. Be aware that the information you share
                on the platform can also be used in case of a data breach. We cannot guarantee absolute security.
            </p>
        </div>
        <div class="heading text-start mt-3 px-3 container">
            <h2 class="fs-3 text-uppercase fw-bold">
                Links to Third-Party Websites
            </h2>
            <p>
                As an affiliate company, we may have content, coupons, banners, or blogs leading to third-party sites.
                Appropriate disclosure will be made whenever there are links to third-party websites. Any information,
                including signing up on third-party websites, falls under their privacy policies. We assume no
                responsibility for the content on third-party websites.

            </p>
        </div>
        <div class="heading text-start mt-3 px-3 container">
            <h2 class="fs-3 text-uppercase fw-bold">
                Amendments to the Privacy Policy

            </h2>
            <p>
                We may update this Privacy Policy at any time at our sole discretion. We will notify you by updating this
                page or sharing a copy via email. Please review this policy periodically.

            </p>
        </div>
    </main>
    @push('js')
    @endpush
@endsection
